# Generated by Django 5.1.7 on 2025-04-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskItem',
        ),
    ]
