# Generated by Django 5.1.7 on 2025-04-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0002_delete_taskitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('zone_id', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=10)),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_code', models.CharField(max_length=10, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('fips_code', models.CharField(max_length=10)),
                ('zone_type', models.CharField(max_length=1)),
                ('direction', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
