# Generated by Django 5.1.7 on 2025-04-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0003_weatherzone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherzone',
            old_name='fips_code',
            new_name='fipsCode',
        ),
        migrations.RenameField(
            model_name='weatherzone',
            old_name='zone_code',
            new_name='zoneCode',
        ),
        migrations.RenameField(
            model_name='weatherzone',
            old_name='zone_id',
            new_name='zoneId',
        ),
        migrations.RenameField(
            model_name='weatherzone',
            old_name='zone_name',
            new_name='zoneName',
        ),
        migrations.RenameField(
            model_name='weatherzone',
            old_name='zone_type',
            new_name='zoneType',
        ),
    ]
