# Generated by Django 5.1.7 on 2025-04-09 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streamSource', models.CharField(blank=True, max_length=255, null=True)),
                ('streamSourceName', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('nearbyPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('isPolling', models.BooleanField(blank=True, default=False)),
                ('lastPollDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mediaFile', models.ImageField(upload_to='uploads/')),
                ('uploadedDate', models.DateTimeField(auto_now_add=True)),
                ('locationName', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction', models.IntegerField(blank=True, null=True)),
                ('predictionString', models.CharField(blank=True, max_length=255, null=True)),
                ('isManualUpload', models.BooleanField(default=False, null=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediaFiles', to='RealTimeMonitor.feedsource')),
            ],
        ),
    ]
