# Generated by Django 5.1.7 on 2025-03-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0002_rename_todoitem_taskitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='completedDate',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
