# Generated by Django 5.1.7 on 2025-03-15 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0003_remove_taskitem_completeddate_taskitem_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mediaFile', models.ImageField(upload_to='uploads/')),
                ('uploadedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
