# Generated by Django 5.1.7 on 2025-03-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0005_mediafile_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='locationName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='predictionString',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='prediction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
