# Generated by Django 5.1.7 on 2025-03-21 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0006_mediafile_locationname_mediafile_predictionstring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streamSource', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('nearbyPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('isPolling', models.BooleanField(default=False)),
                ('lastPollDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mediafile',
            name='isManualUpload',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
