# Generated by Django 5.1.7 on 2025-03-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0007_feedsource_mediafile_ismanualupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='streamSourceName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
