# Generated by Django 5.1.7 on 2025-03-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0008_feedsource_streamsourcename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='isPolling',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
