# Generated by Django 5.1.7 on 2025-03-25 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealTimeMonitor', '0009_alter_feedsource_ispolling'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediaFiles', to='RealTimeMonitor.feedsource'),
        ),
    ]
